server:
  port: 0

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://config-server:8888}
  cloud:
    config:
      fail-fast: false
#Move to repo
  jpa:
    hibernate:
      ddl-auto: none
jwt:
  expiration: 900
  secret-key: "fbuVwHzCoJrhyC0UvnMeq8B6GXQ36uaqWKrb8a7Ch0Y"
security:
  root-user-name: "admin"
  root-user-password: "odministrator"
  root-user-email: "admin@corp.com"
  root-user-role: "ADMIN"
